name: Dev Terraform Destroy

on:
  workflow_dispatch:   # manual trigger only
    inputs:
      confirm:
        description: "Type 'yes' to confirm apply in dev"
        required: true
        default: "no"

jobs:
  terraform-destroy:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    environment: dev
    env:
      VAR_BACKEND: dev
      AWS_REGION: "us-east-1"
    defaults:
      run:
        working-directory: ./dev

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
      
      # Check aws connection and user identity
      - name: Verify AWS CLI
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=${VAR_BACKEND}-backend.hcl

      - name: Terraform Destroy
        run: terraform destroy -var-file="dev.tfvars" -auto-approve
